name: Support request
description: Report a bug that you found, e.g. something is not working as expected
# title: ""
labels: ["support"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Before opening a support request, please check first [How to troubleshoot](https://mynamebestname.github.io/venus-os_dbus-serialbattery_docs/troubleshoot/) and the [FAQ (Frequently Asked Questions)](https://mynamebestname.github.io/venus-os_dbus-serialbattery_docs/faq/) page

        In the case you have difficulties to write in english, try the [deepl.com](https://www.deepl.com) translator.

        ## 🚨 IMPORTANT 🚨

        * Please carefully read all the instructions below including the descriptions! Very often we have to request the data again, because it was not provided in the first place.

        * Please try the `nightly` build first, if you are not already using it. It's very likely that the bug is already fixed. See [here](https://mynamebestname.github.io/venus-os_dbus-serialbattery_docs/general/install#nightly-build) how to install it.

        * Please read the complete [changelog](https://github.com/mynamebestname/dbus-serialbattery/blob/master/CHANGELOG.md).

  - type: textarea
    id: description
    attributes:
      label: Describe the problem
      description: A clear and concise description of what the problem is. Paste also screenshots and pictures, if needed. The more informations you give, the faster we find a solution.
      placeholder: |
        NOTE: Paste the logfields in the appropriate field below.
    validations:
      required: true

  - type: input
    id: driver_version_installed
    attributes:
      label: Driver version of the currently installed driver
      description: |
        Visible in the [driver log files](https://mynamebestname.github.io/venus-os_dbus-serialbattery_docs/troubleshoot/#driver-log-files) or in the remote console/GUI under `SerialBattery` -> `Device` -> `Firmware version`.

        ⚠️ **IMPORTANT:** Do not write `latest` and specify the exact version number, else we cannot help you.
      placeholder: e.g. v1.0.20230927beta
    validations:
      required: true

  - type: input
    id: driver_version_last_working
    attributes:
      label: Driver version of the last known working driver
      description: |
        Insert the version of the driver where the bug was not present. If you don't know, leave it empty.
      placeholder: e.g. v1.0.20230927beta
    validations:
      required: false

  - type: dropdown
    id: venus_os_device_type
    attributes:
      label: Venus OS device type
      description: Select your Venus OS device type.
      multiple: false
      # https://github.com/victronenergy/venus/wiki/machines
      options:
        - Please select
        - CCGX
        - Cerbo GX
        - Ekrano GX
        - GX Card (integrated in Victron device)
        - Octo GX
        - Raspberry Pi
        - VANcu GX
        - Venus_GX
    validations:
      required: true

  - type: input
    id: venus_os_version
    attributes:
      label: Venus OS version
      description: |
        Visible in the remote console/GUI under `Settings` -> `Firmware` -> `Firmware version`

        ⚠️ **IMPORTANT:** Do not write `latest` and specify the exact version number, else we cannot help you.
      placeholder: e.g. v2.94
    validations:
      required: true

  - type: dropdown
    id: bms_type
    attributes:
      label: BMS type
      description: Select your used BMS type.
      multiple: true
      # https://mynamebestname.github.io/venus-os_dbus-serialbattery_docs/general/supported-bms
      options:
        - ANT BMS
        - Daly BMS
        - ECS GreenMeter
        - EG4 LiFePower (Revov, Tian Power)
        - EG4 LL
        - Hektec Modbus SmartBMS / YanYang BMS
        - HLPdata BMS4S
        - Jiabaida JDB BMS (LLT Power, Overkill Solar, Smart BMS)
        - JKBMS (Heltec BMS)
        - JKBMS Inverter
        - MNB spi BMS
        - Renogy BMS
        - Seplos
        - Seplos v3
        - Sinowealth
    validations:
      required: true

  - type: input
    id: cell_count
    attributes:
      label: Cell count
      description: Specify how many cells your battery has.
    validations:
      required: true

  - type: input
    id: battery_count
    attributes:
      label: Battery count
      description: Specify how many batteries/BMS are connected to your Venus OS.
    validations:
      required: true

  - type: dropdown
    id: connection_type
    attributes:
      label: Connection type
      description: Select how you connected your battery to the Venus OS device.
      multiple: false
      options:
        - Please select
        - Serial USB adapter to TTL
        - Serial USB adapter to RS485
        - Raspberry Pi RS485 HAT
        - Bluetooth
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Config file
      description: |
        Paste your `config.ini` file here. See [here](https://mynamebestname.github.io/venus-os_dbus-serialbattery_docs/general/install#settings-locationpath) where you can find it. DO NOT COPY the `config.default.ini` here. The content will be automatically formatted into code, so no need for backticks.
      render: ini
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Please copy and paste any relevant log output here. See [here](https://mynamebestname.github.io/venus-os_dbus-serialbattery_docs/troubleshoot/#driver-log-files) how to get the driver log files. The content will be automatically formatted into code, so no need for backticks.
        ⚠️ **IMPORTANT:** Do not forget to pipe the output through `tai64nlocal`, if you don't copy the commands from the documentation.
      render: shell
    validations:
      required: true

  - type: textarea
    id: other
    attributes:
      label: Any other information that may be helpful
      description: Leave empty, if you already said all
